# Use Node.js v14 as base image
FROM node:14

# Set working directory inside the container
WORKDIR /

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy compiled TypeScript files to the container
COPY dist/ ./

# Expose port that your API runs on
EXPOSE 3000

# Start the API
CMD ["npm", "start"]
